### ISSUE TITLE
Status on Binance Smart Chain nodes issue

### ISSUE THREAD

**Issue by ChefKai** [pancakeswap/pancake-subgraph#50]
Hello everyone 👋 

Recently, Binance Smart Chain has been impacted with multiple issues related to nodes (full and archive); as a result, most of our subgraphs, on both self-hosting and TheGraph, have stopped syncing or have a significant delay in processing new data (blocks/transactions). We are sorry for the inconvenience, and are working to bring back our subgraphs up to the latest block.

In order to keep track with the PancakeSwap ecosystem, you can access tokens/pairs data using:
- BitQuery: [Example (v1)](https://bitquery.io/blog/pancake-swap-dex-apis)
- Covalent: [Documentation](https://www.covalenthq.com/docs/api/#overview)

Both of them support v1, and v2 ecosystem.

If you wish to follow the status for the Binance Smart Chain network on TheGraph, please refer to [status.thegraph.com](https://status.thegraph.com) ([incident 1](https://status.thegraph.com/incidents/lp0c97hbyfvn) / [incident 2](https://status.thegraph.com/incidents/zm3mfjy6lpnx)).

If you are hosting a BSC node, please refer to [binance-chain/bsc](https://github.com/binance-chain/bsc) repository.

Thank you for your support; keep building!

**Comment by buddies2705** [comment]
Bitquery also has Pancake V2., Check examples here (https://graphql.bitquery.io)

**Comment by fxmarty** [comment]
Thanks a lot for the update! Do you think it would be more a matter of days, weeks or months for the issue to be solved? To see if it is worth for me looking into BitQuery / Covalent, or rather waiting.

Something I have been surprised of is to see fully synced subgraphs:
https://thegraph.com/explorer/subgraph/hassan6761/karahi
https://thegraph.com/explorer/subgraph/henry0717/pancakeswapv2

However, I could not manage to have queries working on them (at least for swaps data), and one of them has 12M+ blocks synced, while BSC is <8M. Strange.

**Comment by Amaziinq** [comment]
Truly hope to see it fixed. Thanks.

**Comment by dhelland** [comment]
Any update on this? Thanks!

**Comment by Teedo145** [comment]
Any estimation on when this will be fixed?

**Comment by pavs94** [comment]
The graph seems to show the issue is resolved. Really hope the exchange subgraph is working soon.

**Comment by ChefKai** [comment]
Hello everyone 👋 

Happy to share with you that [TheGraph and Binance Smart Chain nodes issue](https://status.thegraph.com/incidents/zm3mfjy6lpnx) has been resolved! 🎉 
We already have started looking at each of our subgraph referenced in our [README](https://github.com/pancakeswap/pancake-subgraph#pancakeswap-subgraph), and re-deploying the ones who suffered from data-loss and/or inaccurate block data (from uncles, ...), along with new features (Pairs/Prediction/Profile)!

Thank you for your patience!

**Comment by 10xSebastian** [comment]
Thanks for your work so far @ChefKai 🙏 

https://thegraph.com/explorer/subgraph/pancakeswap/exchange is still not syncing.

Or did the subgraph endpoint change?

**Comment by zainamroti** [comment]
Any updates on the exchange subgraphs, its still not synced ?

**Comment by ChefKai** [comment]
@spape @Syedzainjeelani As highlighted in previous issues, unfortunately we cannot use TheGraph actually to sync the `exchange` subgraph, this is why we are using StreamingFast to provide this data to you. The `exchange` subgraph currently on TheGraph is for PancakeSwap v1.

Endpoint: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2

Article: https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388

**Comment by pavs94** [comment]
The above endpoint is so slow.  TTFB Around 20-30s on many simple queries.

**Comment by andrew-komo** [comment]
So thegraph still doesn't sync and streamingfast.io is soooo slow as commented above.

How does https://pancakeswap.finance/info pull the data so quickly?

**Comment by edinsoncs** [comment]
Hello community, does anyone have a correct subgraph?

**Comment by keithfrazier98** [comment]
The subgraph https://api.thegraph.com/subgraphs/name/vmatskiv/pancakeswap-v2 is the only fully synced subgraph I can find and it for some reason does not have any up to date data on it. The streamingfast subgraph seems to be the only option to this day.

**Comment by NBMSacha** [comment]
Hello @keithfrazier98, thanks for this update. Can you elaborate on what is not working on the [vmatskiv/pancakeswap-v2](https://api.thegraph.com/subgraphs/name/vmatskiv/pancakeswap-v2) subgraph? Thanks.
